config/routes.rb
Rails.application.routes.draw do
  
  resources :users do
    collection do
      get 'search'
    end
  end
  
  resources :videos
   post 'video/:id' => 'homes#top'
   resources :video, only: [:index, :new, :create,:edit ,:update, :destroy]

    devise_for :admin, controllers: {
      sessions: 'admin/sessions',
    }

    namespace :admin do
      get 'top' => 'homes#top', as: 'top'
      get 'customers/:customer_id/orders' => 'orders#index', as: 'customer_orders'
      resources :customers, only: [:index, :show, :edit, :update]
      resources :items, except: [:destroy]
      resources :orders, only: [:index, :show, :update] do
        resources :order_details, only: [:update]
      end
    end


    devise_for :customers, controllers: {
      sessions: 'public/sessions',
      registrations: 'public/registrations',
    }

    scope module: :public do
      root 'homes#top'

      get 'customers/mypage' => 'customers#show', as: 'mypage'
      get 'customers/information/edit' => 'customers#edit', as: 'edit_information'
      patch 'customers/information' => 'customers#update', as: 'update_information'
      get 'customers/unsubscribe' => 'customers#unsubscribe', as: 'confirm_unsubscribe'
      put 'customers/information' => 'customers#update'
      patch 'customers/withdraw' => 'customers#withdraw', as: 'withdraw_customer'
      delete 'cart_items/destroy_all' => 'cart_items#destroy_all', as: 'destroy_all_cart_items'
      post 'orders/confirm' => 'orders#confirm'
      get 'orders/confirm' => 'orders#error'
      get 'orders/thanks' => 'orders#thanks', as: 'thanks'

      resources :homes

      resources :addresses, only: [:index, :create, :edit, :update, :destroy]
      resources :items, only: [:index, :show] do
        resources :cart_items, only: [:create, :update, :destroy]
      end
      resources :cart_items, only: [:index]
      resources :orders, only: [:new, :index, :create, :show]

    end

      resources :items, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
        resource :favorites, only: [:create, :destroy]
        resources :comments, only: [:create, :destroy]
      end


 end

app/views/layouts/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>エラーが発生しました。以下ご確認お願いいたします。</h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Campman</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>


   <body class="d-flex flex-column vh-100">
    <header class="shadow-sm"<%= (admin_signed_in? ? "admin_header" : "" ) %>>
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          <a class="navbar-brand p-3" href="/"><%= image_tag "logo.jpg", size: "100x100" %></a>
          <%= link_to '', (admin_signed_in? ? admin_top_path : root_path ), class: "logo" %>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if admin_signed_in? %>
              <li class="nav-item"><%= link_to '商品一覧',  admin_items_path, class: 'nav-link text-dark' %></li>
              <li class="nav-item"><%= link_to '会員一覧',  admin_customers_path, class: 'nav-link text-dark' %></li>
              <li class="nav-item"><%= link_to '注文履歴一覧',  admin_orders_path, class: 'nav-link text-dark' %></li>
              <li class="nav-item"><%= link_to 'ログアウト', destroy_admin_session_path, method: :delete, class: 'nav-link text-dark' %></li>
            <% elsif customer_signed_in? %>
              <li class="nav-item"><%= link_to 'マイページ', mypage_path, class: 'nav-link text-dark' %></li>
              <li class="nav-item"><%= link_to '動画投稿フォーム', new_video_path, class: 'nav-link text-dark' %></li>
              <li class="nav-item"><%= link_to '動画一覧', videos_path, class: 'nav-link text-dark' %></li>
              <li class="nav-item"><%= link_to '商品一覧', items_path, class: 'nav-link text-dark' %></li>
              <li class="nav-item"><%= link_to 'カート', cart_items_path, class: 'nav-link text-dark' %></li>
              <li class="nav-item"><%= link_to 'ログアウト', destroy_customer_session_path, method: :delete, class: 'nav-link text-dark' %></li>
            <% else %>
              <li class="nav-item"><%= link_to '商品一覧', items_path, class: 'nav-link text-dark' %></li>
              <li class="nav-item"><%= link_to '新規登録', new_customer_registration_path, class: 'nav-link text-dark' %></li>
              <li class="nav-item"><%= link_to 'ログイン', new_customer_session_path, class: 'nav-link text-dark' %></li>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>

    <main class="mb-auto">
    <%= yield %>
    </main>

    <footer class="bg-dark text-white pt-5 pb-4">
      <div class="container">
        <div class="row no-gutters">
          <div class="col-md-4">
            <%#= image_tag "logo.jpg", size: "70x70" %>
          </div>
          <div class="col-md-8">
            <h6 class="text-white mt-2 mb-3">Copyright © Campman Inc. All Rights Reserved.</h6>
          </div>
        </div>
      </div>
    </footer>
  </body>